package br.com.mmgabri.adapters.grpc.client;

import br.com.mmgabri.application.domains.enums.ServicesEnum;
import br.com.mmgabri.application.exceptions.BusinessException;
import br.com.mmgabri.application.exceptions.ReasonCodeException;
import br.com.mmgabri.application.exceptions.TechnicalException;
import br.com.mmgabri.application.utils.ReasonCodes;
import br.com.itau.debit.authorizer.common.v1.BusinessResult;
import br.com.itau.debit.authorizer.common.v1.ReasonCode;
import com.google.protobuf.InvalidProtocolBufferException;
import com.google.rpc.ErrorInfo;
import io.grpc.StatusRuntimeException;
import io.grpc.protobuf.StatusProto;

import java.util.Optional;

/**
 * Translates a dependency response (gRPC error or declined BusinessResult) into the
 * authorizer exception, with the catalog code:
 * <ul>
 *   <li>error with ErrorInfo → code of whoever detected the cause (e.g. TS02)</li>
 *   <li>error without ErrorInfo → authorizer code: timeout/unavailable per
 *       dependency (TA01..TA12) or outside the protocol (TA90)</li>
 *   <li>code unknown in this catalog version → TA91</li>
 * </ul>
 */
public final class DependencyErrors {

    private DependencyErrors() {
    }

    public static TechnicalException fromException(ServicesEnum service, Exception exception) {
        var serviceName = service.getServiceName();
        if (!(exception instanceof StatusRuntimeException statusException)) {
            return new TechnicalException(serviceName, ReasonCode.REASON_CODE_AUTHORIZER_INTERNAL_ERROR, exception.getMessage());
        }

        var errorInfo = errorInfoOf(statusException);
        if (errorInfo.isPresent()) {
            return fromErrorInfo(serviceName, errorInfo.get(), statusException);
        }

        var status = statusException.getStatus();
        var description = status.getDescription();
        return switch (status.getCode()) {
            case DEADLINE_EXCEEDED -> new TechnicalException(serviceName, service.getTimeoutReasonCode(), description);
            case UNAVAILABLE -> new TechnicalException(serviceName, service.getUnavailableReasonCode(), description);
            default -> new TechnicalException(serviceName, ReasonCode.REASON_CODE_AUTHORIZER_DEPENDENCY_OUTSIDE_PROTOCOL, status.getCode() + ": " + description);
        };
    }

    public static ReasonCodeException fromDeclined(ServicesEnum service, BusinessResult result) {
        var serviceName = service.getServiceName();
        var reasonCode = result.getReasonCode();
        if (reasonCode == ReasonCode.UNRECOGNIZED) {
            var description = "reasonCode=" + result.getReasonCodeValue() + ": " + result.getMessage();
            return new TechnicalException(serviceName, ReasonCode.REASON_CODE_AUTHORIZER_UNRECOGNIZED_REASON_CODE, description);
        }
        return new BusinessException(serviceName, reasonCode, result.getMessage());
    }

    /**
     * ErrorInfo carried in the error trailer. Empty when the error does not follow
     * the protocol (timeout/connection generated by the gRPC library, or status without details).
     */
    private static Optional<ErrorInfo> errorInfoOf(StatusRuntimeException statusException) {
        var status = StatusProto.fromThrowable(statusException);
        if (status == null) {
            return Optional.empty();
        }
        for (var detail : status.getDetailsList()) {
            if (detail.is(ErrorInfo.class)) {
                try {
                    var errorInfo = detail.unpack(ErrorInfo.class);
                    return Optional.of(errorInfo);
                } catch (InvalidProtocolBufferException e) {
                    return Optional.empty();
                }
            }
        }
        return Optional.empty();
    }

    private static TechnicalException fromErrorInfo(String serviceName, ErrorInfo errorInfo, StatusRuntimeException statusException) {
        var reason = errorInfo.getReason();
        var description = statusException.getStatus().getDescription();
        var reasonCode = ReasonCodes.fromCode(reason);

        if (reasonCode.isEmpty()) {
            var detail = "reason=" + reason + " domain=" + errorInfo.getDomain() + ": " + description;
            return new TechnicalException(serviceName, ReasonCode.REASON_CODE_AUTHORIZER_UNRECOGNIZED_REASON_CODE, detail);
        }
        if (ReasonCodes.isBusiness(reasonCode.get())) {
            // A business decline must not arrive as a gRPC error.
            var detail = "business reason as gRPC error: " + reason + ": " + description;
            return new TechnicalException(serviceName, ReasonCode.REASON_CODE_AUTHORIZER_DEPENDENCY_OUTSIDE_PROTOCOL, detail);
        }
        return new TechnicalException(serviceName, reasonCode.get(), description);
    }
}
