syntax = "proto3";
option java_multiple_files = true;
package br.com.mmgabri.grpc;

import "comuns/header_message_grpc.proto";

service AutorizadorService {
    rpc AutorizarTransacao (AutorizadorRequest) returns (AutorizadorResponse);
}
message AutorizadorRequest {
    br.com.mmgabri.grpc.comuns.HeaderMessageGrpc headerMessageGrpc = 1;
    map<string, string> messageIso = 2;

    string customReturnDataEnrichment = 3;
    int32 sleepDataEnrichment = 4;

    string customReturnRules = 5;
    int32 sleepRules = 6;

    string customReturnSeguranca = 7;
    int32 sleepSeguranca = 8;

    string customReturnLimit = 9;
    int32 sleepLimitEfetivacao = 10;
    int32 sleepLimitSimulacao = 11;

    string customReturnLedger = 12;
    int32 sleepLedgerEfetivacao = 13;
    int32 sleepLedgerSimulacao = 14;

    string customReturnFraude = 15;
    int32 sleepFraude = 16;

    string transactionIdReversal = 17;
}

message AutorizadorResponse {
    br.com.mmgabri.grpc.comuns.HeaderMessageGrpc headerMessageGrpc = 1;
    map<string, string> messageIso = 2;
}