spring:
  threads:
    virtual:
      enabled=true:

server:
  port: 9097

logging:
  level:
    br.com.mmgabri: info

management:
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  datadog:
    metrics:
      export:
        apiKey: c735d4be91ef0ab5e9292c5a50a6ee6b
        step: 5s
        uri: https://us5.datadoghq.com/
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus