syntax = "proto3";
option java_multiple_files = true;
package br.com.mmgabri.grpc;

import "comuns/header_message_grpc.proto";

service AutorizadorService {
    rpc AutorizarTransacao (AutorizadorRequest) returns (AutorizadorResponse);
}
message AutorizadorRequest {
    br.com.mmgabri.grpc.comuns.HeaderMessageGrpc headerMessageGrpc = 1;
    map<string, string> messageIso = 2;
    string customReturnDataEnrichment = 3;
    string customReturnSeguranca = 4;
    string customReturnLimitePortador = 5;
    string customReturnLimite = 6;
    string customReturnLancamentoConta = 7;
    string customReturnFraude = 8;
    string transactionIdReversal = 9;
    int32 sleepDataEnrichment = 10;
    int32 sleepSeguranca = 11;
    int32 sleepLimitePortador = 12;
    int32 sleepLimite = 13;
    int32 sleepLancamentoConta = 14;
    int32 sleepFraude = 15;
}

message AutorizadorResponse {
    br.com.mmgabri.grpc.comuns.HeaderMessageGrpc headerMessageGrpc = 1;
    map<string, string> messageIso = 2;
}