syntax = "proto3";
option java_multiple_files = true;
package br.com.mmgabri.grpc;

import "comuns/header_message_grpc.proto";

service LimitePortadorService {
    rpc AtualizarLimitePortador (LimitePortadorRequest) returns (LimitePortadorResponse);
}

message LimitePortadorRequest {
    br.com.mmgabri.grpc.comuns.HeaderMessageGrpc headerMessageGrpc = 1;
    string contaId = 2;
    string valor = 3;
    string type = 4;
    string customReturnLimitePortador = 5;
    int32 sleepLimitePortador = 6;
}

message LimitePortadorResponse {
    br.com.mmgabri.grpc.comuns.HeaderMessageGrpc headerMessageGrpc = 1;
    string contaId = 2;
    bool aprovado = 3;
    string errorCode = 4;
    string errorDescription = 5;
}

