spring:
  threads:
    virtual:
      enabled: true
  grpc:
    client:
      channel:
        autorizador:
          target: dns:///autorizador-debito-svc.autorizador-debito.svc.cluster.local:59091
          keepalive:
            time: 60s
            timeout: 60s
          idle:
            timeout: 60s

server:
  port: 9090

grpc:
  autorizador-client:
    timeout: 6000

logging:
  level:
    br.com.mmgabri: ${LOGGING_LEVEL:INFO}

aws:
  sqs:
    region: "us-east-1"
    reversal-queue-name: "queue-reversal-notification"

management:
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  datadog:
    metrics:
      export:
        apiKey: ${DD_API_KEY}
        step: 5s
        uri: https://us5.datadoghq.com/
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus