spring:
  threads:
    virtual:
      enabled=true:
server:
  port: 9090

grpc:
  autorizador-client:
    port: 59091
    host: autorizador-debito-service.autorizador-debito.local
    timeout: 6000

logging:
  level:
    br.com.mmgabri: DEBUG

aws:
  sqs:
    region: "us-east-1"
    reversal-queue-name: "queue-authorization-reversal"

management:
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  datadog:
    metrics:
      export:
        apiKey: ${DD_API_KEY}
        step: 5s
        uri: https://us5.datadoghq.com/
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus