spring:
  threads:
    virtual:
      enabled=true:

server:
  port: 9090

grpc:
  autorizador-client:
    port: 59091
    host: localhost
    timeout: 50000

aws:
  sqs:
    region: "us-east-1"
    reversal-queue-name: "queue-reversal-notification"

logging:
  level:
    br.com.mmgabri: DEBUG

management:
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  datadog:
    metrics:
      export:
        apiKey: 1bfbce8c2e8ed2aeb6dcd33f55f207ff
        step: 5s
        uri: https://us5.datadoghq.com/
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus