server:
  port: 9095

grpc:
  server:
    port: 59095
  client:
    user-service:
      negotiationType: PLAINTEXT

custom:
  sleep: 1

logging:
  level:
    io.grpc.netty.shaded.io.netty: ERROR
    io.grpc.netty.shaded.io.netty.handler.codec.http2: ERROR
