spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 100
            readTimeout: 500
          fraudesClient:
            connectTimeout: 100
            readTimeout: 500
  threads:
    virtual:
      enabled: true
  config:
    import: "classpath:products_config.yml"
  datasource:
    url: jdbc:h2:mem:autorizador_debito;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: false
        show_sql: false

server:
  port: 8081

rest:
  clients:
    fraudes:
      url: "http://fraudes-service.autorizador-debito.local:8087/api/fraudes"

grpc:
  server:
    port: 59091
    host: localhost
  enrichment-service-client:
    port: 59092
    host: enrichment-service.autorizador-debito.local
    timeout: 1500
  security-service-client:
    port: 58104
    host: security-service.autorizador-debito.local
    timeout: 15000
  rules-service-client:
    port: 59093
    host: rules-service.autorizador-debito.local
    timeout: 15000
  limit-service-client:
    port: 59095
    host: limit-service.autorizador-debito.local
    timeout: 1500
  ledger-service-client:
    port: 59096
    host: ledger-service.autorizador-debito.local
    timeout: 1500
  antifraud-service-client:
    port: 59097
    host: antifraud-service.autorizador-debito.local
    timeout: 1500

custom:
  sleep: 1000
  database-memo: ${DATABASE_MEMO}
  database-mode-async: ${DATABASE_MODE_ASYNC}

logging:
  level:
    br.com.mmgabri: ${LOGGING_LEVEL}

management:
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  datadog:
    metrics:
      export:
        apiKey: ${DD_API_KEY}
        step: 5s
        uri: https://us5.datadoghq.com/
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
