spring:
  threads:
    virtual:
      enabled: true
  config:
    import: "classpath:products_config.yml"

server:
  port: 9091

grpc:
  server:
    port: 59091
    host: localhost
  enrichment-service-client:
    port: 59092
    host: localhost
    timeout: 3600000
  security-service-client:
    port: 59094
    host: localhost
    timeout: 3600000
  rules-service-client:
    port: 59093
    host: localhost
    timeout: 3600000
  limit-service-client:
    port: 59095
    host: localhost
    timeout: 3600000
  ledger-service-client:
    port: 59096
    host: localhost
    timeout: 3600000
  antifraud-service-client:
    port: 59097
    host: localhost
    timeout: 3600000

aws:
  sqs:
    reversal-notification-queue-url: "https://sqs.us-east-1.amazonaws.com/000000000000/queue-reversal-notification"

custom:
  database-mode-async: true

logging:
  level:
    br.com.mmgabri: debug

management:
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  datadog:
    metrics:
      export:
        apiKey: 7d84e7dd51f775e36ac5bf9a76257567
        step: 5s
        uri: https://us5.datadoghq.com/
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
