spring:
  threads:
    virtual:
      enabled: true
  config:
    import: "classpath:products_config.yml"

server:
  port: 9091

grpc:
  server:
    port: 59091
    host: localhost
  enrichment-service-client:
    port: 59092
    host: enrichment-service-svc.autorizador-debito.local
    timeout: 1500
  security-service-client:
    port: 59094
    host: security-service-svc.autorizador-debito.local
    timeout: 15000
  rules-service-client:
    port: 59093
    host: rules-service-svc.autorizador-debito.local
    timeout: 15000
  limit-service-client:
    port: 59095
    host: limit-service-svc.autorizador-debito.local
    timeout: 1500
  ledger-service-client:
    port: 59096
    host: ledger-service-svc.autorizador-debito.local
    timeout: 1500
  antifraud-service-client:
    port: 59097
    host: antifraud-service-svc.autorizador-debito.local
    timeout: 1500

aws:
  sqs:
    reversal-notification-queue-name: "queue-compensation-transaction"

custom:
  database-mode-async: ${DATABASE_MODE_ASYNC}

logging:
  level:
    br.com.mmgabri: ${LOGGING_LEVEL}

management:
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  datadog:
    metrics:
      export:
        apiKey: ${DD_API_KEY}
        step: 5s
        uri: https://us5.datadoghq.com/
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus