spring:
  threads:
    virtual:
      enabled: true
  config:
    import: "classpath:products_config.yml"

server:
  port: 9091

grpc:
  server:
    port: 59091
    host: localhost
  enrichment-service-client:
    port: 59092
    host: localhost
    timeout: 3600000
  security-service-client:
    port: 59094
    host: localhost
    timeout: 3600000
  rules-service-client:
    port: 59093
    host: localhost
    timeout: 3600000
  limit-service-client:
    port: 59095
    host: localhost
    timeout: 3600000
  ledger-service-client:
    port: 59096
    host: localhost
    timeout: 3600000
  antifraud-service-client:
    port: 59097
    host: localhost
    timeout: 3600000

aws:
  sqs:
    compensation-transaction-queue-name: "queue-compensation-transaction"

custom:
  database-mode-async: false

logging:
  level:
    br.com.mmgabri: debug

management:
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  datadog:
    metrics:
      export:
        apiKey: 1bfbce8c2e8ed2aeb6dcd33f55f207ff
        step: 5s
        uri: https://us5.datadoghq.com/
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
