spring:
  threads:
    virtual:
      enabled: true
  config:
    import: "classpath:products_config.yml"
  data:
    redis:
      host: ${REDIS_HOST:}
      port: 6379
  grpc:
    server:
      port: 59091
    client:
      channel:
        enrichment:
          target: dns:///enrichment-service-svc.autorizador-debito.svc.cluster.local:59092
          keepalive:
            time: 60s
            timeout: 60s
          idle:
            timeout: 60s
        rules:
          target: dns:///rules-service-svc.autorizador-debito.svc.cluster.local:59093
          keepalive:
            time: 60s
            timeout: 60s
          idle:
            timeout: 60s
        security:
          target: dns:///security-service-svc.autorizador-debito.svc.cluster.local:59094
          keepalive:
            time: 60s
            timeout: 60s
          idle:
            timeout: 60s
        limit:
          target: dns:///limit-service-svc.autorizador-debito.svc.cluster.local:59095
          keepalive:
            time: 60s
            timeout: 60s
          idle:
            timeout: 60s
        ledger:
          target: dns:///ledger-service-svc.autorizador-debito.svc.cluster.local:59096
          keepalive:
            time: 60s
            timeout: 60s
          idle:
            timeout: 60s
        antifraud:
          target: dns:///antifraud-service-svc.autorizador-debito.svc.cluster.local:59097
          keepalive:
            time: 60s
            timeout: 60s
          idle:
            timeout: 60s

server:
  port: 9091

grpc:
  enrichment-service-client:
    timeout: 1500
  security-service-client:
    timeout: 15000
  rules-service-client:
    timeout: 15000
  limit-service-client:
    timeout: 1500
  ledger-service-client:
    timeout: 1500
    completion-timeout: 600
  antifraud-service-client:
    timeout: 1500

aws:
  sqs:
    compensation-transaction-queue-name: "queue-compensation-transaction"
    comando-conta-queue-name: "queue-comando-conta"

custom:
  database-mode-async: ${DATABASE_MODE_ASYNC}

logging:
  level:
    br.com.mmgabri: ${LOGGING_LEVEL}

management:
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  datadog:
    metrics:
      export:
        apiKey: ${DD_API_KEY}
        step: 5s
        uri: https://api.datadoghq.com/
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus