server:
  port: 9098

grpc:
  ledger-service-client:
    port: 59096
    host: ledger-service.autorizador-debito.local
    timeout: 1100

custom:
  sleep: 1

aws:
  sqs:
    enabled: true
    region: "us-east-1"
    queue-name: "queue-comando-conta"
    max-messages: 10
    wait-time-seconds: 20
    visibility-timeout-seconds: 30
    error-backoff-millis: 2000
    consumer-threads: 10

logging:
  level:
    br.com.mmgabri: info