server:
  port: 9098

grpc:
  ledger-service-client:
    port: 59096
    host: ledger-service-svc.autorizador-debito.local
    timeout: 1100

custom:
  sleep: 1

aws:
  sqs:
    enabled: true
    region: "us-east-1"
    queue-name: "queue-comando-conta"
    max-messages: 10
    wait-time-seconds: 20
    visibility-timeout-seconds: 30
    error-backoff-millis: 2000
    poll-threads: 5
    consumer-threads: 50

logging:
  level:
    br.com.mmgabri: ${LOGGING_LEVEL:INFO}

management:
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  datadog:
    metrics:
      export:
        apiKey: ${DD_API_KEY}
        step: 5s
        uri: https://us5.datadoghq.com/
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus