server:
  port: 9098

spring:
  threads:
    virtual:
      enabled: true
  grpc:
    client:
      channel:
        ledger:
          target: dns:///localhost:59096
          keepalive:
            time: 60s
            timeout: 60s
          idle:
            timeout: 60s

grpc:
  ledger-service-client:
    timeout: 5000

aws:
  sqs:
    enabled: true
    region: "us-east-1"
    queue-name: "queue-comando-conta"
    max-messages: 10
    wait-time-seconds: 20
    visibility-timeout-seconds: 30
    error-backoff-millis: 2000
    poll-threads: 5
    consumer-threads: 50

logging:
  level:
    br.com.mmgabri: DEBUG

management:
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  datadog:
    metrics:
      export:
        apiKey: 35ca9af351b9a33a19bce59652d93092
        step: 5s
        uri: https://api.datadoghq.com/
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
