server:
  port: 9096

spring:
  threads:
    virtual:
      enabled: true
  grpc:
    server:
      port: 59096
  data:
    redis:
      host: 127.0.0.1
      port: 6379

aws:
  sqs:
    enabled: true
    region: "us-east-1"
    queue-name: "queue-comando-conta"
    max-messages: 10
    wait-time-seconds: 20
    visibility-timeout-seconds: 30
    error-backoff-millis: 2000
    poll-threads: 5
    consumer-threads: 50

custom:
  sleep: 1

logging:
  level:
    br.com.mmgabri: DEBUG
  pattern:
    level: "%5p [ledger-service=${INSTANCIA_IP:localhost}]"

management:
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  datadog:
    metrics:
      export:
        apiKey: 35ca9af351b9a33a19bce59652d93092
        step: 5s
        uri: https://us5.datadoghq.com/
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
