server:
  port: 9096

spring:
  threads:
    virtual:
      enabled: true
  grpc:
    server:
      port: 59096
  data:
    redis:
      host: ${REDIS_HOST:}
      port: 6379

aws:
  sqs:
    region: "us-east-1"
    comando-conta-queue-name: "queue-comando-conta"

app:
  async:
    response-timeout: 700ms

logging:
  level:
    br.com.mmgabri: ${LOGGING_LEVEL:INFO}
  pattern:
    level: "%5p [ledger-service=${INSTANCIA_IP:localhost}]"

management:
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  datadog:
    metrics:
      export:
        apiKey: ${DD_API_KEY}
        step: 5s
        uri: https://api.datadoghq.com/
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
