server:
  port: 9096

spring:
  threads:
    virtual:
      enabled: true
  grpc:
    server:
      port: 59096
  data:
    redis:
      host: ${REDIS_HOST:}
      port: 6379

aws:
  sqs:
    enabled: true
    region: "us-east-1"
    queue-name: "queue-comando-conta"
    max-messages: 10
    wait-time-seconds: 20
    visibility-timeout-seconds: 120
    error-backoff-millis: 1000
    poll-threads: 20
    consumer-threads: 500

custom:
  sleep: 1

logging:
  level:
    br.com.mmgabri: ${LOGGING_LEVEL:INFO}
  pattern:
    level: "%5p [ledger-service=${INSTANCIA_IP:localhost}]"

management:
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  datadog:
    metrics:
      export:
        apiKey: ${DD_API_KEY}
        step: 5s
        uri: https://api.datadoghq.com/
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
